export const perms = [
  "orders.read",
  "orders.create",
  "orders.edit",
  "orders.assign",
  "orders.transition",
  "orders.issue",
  "orders.reopen",
  "contacts.read",
  "finance.read",
  "finance.write",
  "templates.manage",
  "data.export",
  "data.import",
  "billing.manage",
  "warehouse.manage",
];
export const names = [
  "Просмотр заказов",
  "Приём устройств",
  "Редактирование",
  "Назначение мастеров",
  "Изменение этапов",
  "Выдача",
  "Повторное открытие",
  "Контакты клиентов",
  "Просмотр финансов",
  "Сметы и оплаты",
  "Формы и процессы",
  "Экспорт",
  "Импорт",
  "Подписка",
  "Склад",
];
export const label = (p) => names[perms.indexOf(p)] || p;
export const empty = () => ({
  key: "field_" + crypto.randomUUID().slice(0, 8),
  label: "",
  type: "string",
  section: "Приём",
  width: 1,
  row: null,
  required: false,
  options: [],
  condition: null,
  read_permission: null,
  write_permission: null,
});
export const types = {
  string: "Короткий текст",
  text: "Длинный текст",
  number: "Число",
  date: "Дата",
  image: "Фото",
  select: "Список",
  checkbox: "Флажок",
};
